apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-method-routing
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/server-snippet: |
      location /api/books {
        if ($request_method = GET) {
          rewrite ^/api/books(.*)$ /get$1 break;
        }
        if ($request_method = POST) {
          rewrite ^/api/books(.*)$ /post$1 break;
        }
        if ($request_method = PUT) {
          rewrite ^/api/books(.*)$ /put$1 break;
        }
        if ($request_method = DELETE) {
          rewrite ^/api/books(.*)$ /delete$1 break;
        }
      }
spec:
  rules:
    - http:
        paths:
          - path: /get
            pathType: Prefix
            backend:
              service:
                name: get-service
                port:
                  number: 3030

          - path: /post
            pathType: Prefix
            backend:
              service:
                name: post-service
                port:
                  number: 3030

          - path: /put
            pathType: Prefix
            backend:
              service:
                name: put-service
                port:
                  number: 3030

          - path: /delete
            pathType: Prefix
            backend:
              service:
                name: delete-service
                port:
                  number: 3030

          - path: /render
            pathType: Prefix
            backend:
              service:
                name: render-service
                port:
                  number: 3030
