apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-method-routing
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      location /api {
        if ($request_method = GET) {
          rewrite ^/api(.*)$ /get$1 break;
        }
        if ($request_method = POST) {
          rewrite ^/api(.*)$ /post$1 break;
        }
        if ($request_method = PUT) {
          rewrite ^/api(.*)$ /put$1 break;
        }
        if ($request_method = DELETE) {
          rewrite ^/api(.*)$ /delete$1 break;
        }
      }
spec:
  rules:
    - http:
        paths:
          - path: /get
            pathType: Prefix
            backend:
              service:
                name: get-service-service
                port:
                  number: 3030
          - path: /post
            pathType: Prefix
            backend:
              service:
                name: post-service-service
                port:
                  number: 3030
          - path: /put
            pathType: Prefix
            backend:
              service:
                name: put-service-service
                port:
                  number: 3030
          - path: /delete
            pathType: Prefix
            backend:
              service:
                name: delete-service-service
                port:
                  number: 3030
          - path: /render
            pathType: Prefix
            backend:
              service:
                name: render-service-service
                port:
                  number: 3030
