apiVersion: apps/v1
kind: Deployment
metadata:
  name: put-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: put-service
  template:
    metadata:
      labels:
        app: put-service
    spec:
      containers:
        - name: put-service
          image: mostafahtm/put_service:latest
          imagePullPolicy: "Always"
          env:
            - name: TZ
              value: Europe/Berlin
            - name: MONGO_URI
              value: "mongodb://bookuser:bookpass@mongo:27017/exercise-4?authSource=exercise-4"
          ports:
            - containerPort: 3030
